output_dir: {your folder}

MODEL:
  model: 'model_nefnet'
  jitter_factor: 2.5
  theta_L: 1

SOLVER:
  loss_factor: [0.5, 0.5, 1]
  epochs: 150
  lr: 1e-1
  scheduler: 'MultiStep'
  lr_step: [50, 100]

DATA:
  lead_num: 3
  super_mode: 'IIv2v5_v4I_372'
  train_data_mode: 'input_fix'
  noise: False

latent_save_dir: {your folder}
